/**
 * Terms of Service Page
 * KLIQT Media terms and conditions for service usage
 */

'use client'

import { motion } from 'framer-motion'
import { 
  FileText, 
  Scale, 
  Shield, 
  CreditCard, 
  Users, 
  AlertTriangle,
  CheckCircle,
  XCircle,
  Gavel,
  Globe
} from 'lucide-react'
import Link from 'next/link'

const sections = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    icon: CheckCircle,
    content: [
      {
        subtitle: 'Agreement to Terms',
        text: 'By accessing or using KLIQT Media services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services.'
      },
      {
        subtitle: 'Eligibility',
        text: 'You must be at least 18 years old and have the legal capacity to enter into contracts to use our services. By using our services, you represent and warrant that you meet these requirements.'
      },
      {
        subtitle: 'Business Use',
        text: 'Our services are intended for business and professional use. Personal use is permitted but subject to the same terms and conditions outlined herein.'
      }
    ]
  },
  {
    id: 'services',
    title: 'Description of Services',
    icon: Users,
    content: [
      {
        subtitle: 'AI-Powered Solutions',
        text: 'KLIQT Media provides AI-powered content creation, automation tools, and freelancer network services. Our services include but are not limited to content generation, workflow automation, and project management tools.'
      },
      {
        subtitle: 'Freelancer Network',
        text: 'We connect clients with vetted freelancers and creative professionals. We facilitate these connections but are not party to the contracts between clients and freelancers.'
      },
      {
        subtitle: 'Service Availability',
        text: 'We strive to maintain 99.9% uptime but do not guarantee uninterrupted service. We reserve the right to modify, suspend, or discontinue services with reasonable notice.'
      }
    ]
  },
  {
    id: 'user-obligations',
    title: 'User Obligations',
    icon: Shield,
    content: [
      {
        subtitle: 'Acceptable Use',
        text: 'You agree to use our services only for lawful purposes and in accordance with these terms. You will not use our services to create, distribute, or promote illegal, harmful, or offensive content.'
      },
      {
        subtitle: 'Account Security',
        text: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized use.'
      },
      {
        subtitle: 'Content Responsibility',
        text: 'You are solely responsible for any content you create, upload, or distribute using our services. You warrant that you have all necessary rights and permissions for such content.'
      }
    ]
  },
  {
    id: 'payment-terms',
    title: 'Payment Terms',
    icon: CreditCard,
    content: [
      {
        subtitle: 'Subscription Fees',
        text: 'Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as expressly stated in our refund policy.'
      },
      {
        subtitle: 'Payment Processing',
        text: 'Payments are processed through secure third-party payment processors. You authorize us to charge your designated payment method for all applicable fees.'
      },
      {
        subtitle: 'Late Payments',
        text: 'Failure to pay fees when due may result in suspension or termination of your account. We reserve the right to charge late fees and interest on overdue amounts.'
      }
    ]
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    icon: Scale,
    content: [
      {
        subtitle: 'Our IP Rights',
        text: 'KLIQT Media retains all rights, title, and interest in our services, software, and proprietary technology. You may not copy, modify, or reverse engineer our services.'
      },
      {
        subtitle: 'User Content',
        text: 'You retain ownership of content you create using our services. However, you grant us a limited license to use, store, and process your content to provide our services.'
      },
      {
        subtitle: 'AI-Generated Content',
        text: 'Content generated by our AI tools is provided "as is." While you may use AI-generated content, you should review and verify its accuracy and appropriateness for your purposes.'
      }
    ]
  },
  {
    id: 'limitation-liability',
    title: 'Limitation of Liability',
    icon: AlertTriangle,
    content: [
      {
        subtitle: 'Service Disclaimer',
        text: 'Our services are provided "as is" without warranties of any kind. We disclaim all warranties, express or implied, including merchantability and fitness for a particular purpose.'
      },
      {
        subtitle: 'Liability Limits',
        text: 'Our total liability to you for any claims arising from these terms or your use of our services shall not exceed the amount you paid us in the 12 months preceding the claim.'
      },
      {
        subtitle: 'Excluded Damages',
        text: 'We shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits or data, even if we have been advised of the possibility of such damages.'
      }
    ]
  }
]

const prohibitedUses = [
  'Illegal activities or content that violates applicable laws',
  'Harassment, abuse, or harmful content targeting individuals or groups',
  'Spam, unsolicited communications, or fraudulent activities',
  'Malware, viruses, or other harmful code',
  'Unauthorized access to systems or data',
  'Violation of intellectual property rights',
  'Impersonation of others or false representation',
  'Content that promotes violence or illegal activities'
]

export default function TermsPage() {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 }
  }

  return (
    <main className="min-h-screen bg-black text-white">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-black/80 backdrop-blur-md border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="flex items-center space-x-3">
              <img
                src="https://i.ibb.co/B5NV5MR1/kliqtsvg.png"
                alt="KLIQT Media Logo"
                className="h-10 w-auto"
              />
              <span className="text-2xl font-bold neon-text">KLIQT Media</span>
            </Link>
            <div className="hidden md:flex space-x-8">
              <Link href="/#services" className="hover:text-kliqt-primary transition-colors">Services</Link>
              <Link href="/pricing" className="hover:text-kliqt-primary transition-colors">Pricing</Link>
              <Link href="/about" className="hover:text-kliqt-primary transition-colors">About</Link>
              <Link href="/portal" className="hover:text-kliqt-primary transition-colors">Portal</Link>
            </div>
          </div>
        </div>
      </nav>

      <div className="pt-16">
        {/* Hero Section */}
        <section className="py-20 kliqt-gradient-bg">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              className="text-center"
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="flex justify-center mb-6">
                <div className="p-4 bg-kliqt-secondary/10 rounded-2xl">
                  <Gavel className="h-16 w-16 text-kliqt-secondary" />
                </div>
              </div>
              <h1 className="text-4xl md:text-6xl font-bold mb-6">
                Terms of{' '}
                <span className="neon-text">Service</span>
              </h1>
              <p className="text-xl text-gray-300 mb-8">
                These terms govern your use of KLIQT Media services. Please read them carefully 
                as they contain important information about your rights and obligations.
              </p>
              <div className="flex items-center justify-center space-x-4 text-sm text-gray-400">
                <span>Last updated: January 2025</span>
                <span>•</span>
                <span>Effective: January 1, 2025</span>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Quick Navigation */}
        <section className="py-12 bg-gray-900/50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              className="kliqt-card"
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <h2 className="text-2xl font-bold mb-6 flex items-center">
                <FileText className="h-6 w-6 text-kliqt-secondary mr-3" />
                Quick Navigation
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {sections.map((section, index) => (
                  <a
                    key={section.id}
                    href={`#${section.id}`}
                    className="flex items-center p-3 bg-gray-800/50 rounded-lg hover:bg-kliqt-secondary/10 transition-colors group"
                  >
                    <section.icon className="h-5 w-5 text-kliqt-secondary mr-3 group-hover:scale-110 transition-transform" />
                    <span className="text-sm group-hover:text-kliqt-secondary transition-colors">
                      {section.title}
                    </span>
                  </a>
                ))}
              </div>
            </motion.div>
          </div>
        </section>

        {/* Terms Content */}
        <section className="py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="space-y-16">
              {sections.map((section, index) => (
                <motion.div
                  key={section.id}
                  id={section.id}
                  className="kliqt-card"
                  variants={fadeInUp}
                  initial="initial"
                  whileInView="animate"
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                >
                  <div className="flex items-center mb-6">
                    <div className="p-3 bg-kliqt-secondary/10 rounded-xl mr-4">
                      <section.icon className="h-8 w-8 text-kliqt-secondary" />
                    </div>
                    <h2 className="text-3xl font-bold">{section.title}</h2>
                  </div>
                  
                  <div className="space-y-6">
                    {section.content.map((item, itemIndex) => (
                      <div key={itemIndex}>
                        <h3 className="text-xl font-semibold mb-3 text-kliqt-secondary">
                          {item.subtitle}
                        </h3>
                        <p className="text-gray-300 leading-relaxed">
                          {item.text}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Prohibited Uses */}
        <section className="py-20 bg-gray-900/50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              className="kliqt-card"
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div className="flex items-center mb-6">
                <div className="p-3 bg-red-500/10 rounded-xl mr-4">
                  <XCircle className="h-8 w-8 text-red-400" />
                </div>
                <h2 className="text-3xl font-bold">Prohibited Uses</h2>
              </div>
              
              <p className="text-gray-300 mb-6">
                You may not use our services for any of the following purposes:
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {prohibitedUses.map((use, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <XCircle className="h-5 w-5 text-red-400 mt-0.5 flex-shrink-0" />
                    <span className="text-gray-300 text-sm">{use}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </section>

        {/* Additional Terms */}
        <section className="py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <motion.div
                className="kliqt-card"
                variants={fadeInUp}
                initial="initial"
                whileInView="animate"
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
              >
                <div className="flex items-center mb-4">
                  <Globe className="h-6 w-6 text-kliqt-secondary mr-3" />
                  <h3 className="text-xl font-bold">Governing Law</h3>
                </div>
                <p className="text-gray-300 mb-4">
                  These terms are governed by the laws of England and Wales. Any disputes will be 
                  resolved in the courts of London, United Kingdom.
                </p>
                <div className="text-sm text-gray-400">
                  <p>• English law applies</p>
                  <p>• London jurisdiction</p>
                  <p>• Alternative dispute resolution available</p>
                </div>
              </motion.div>

              <motion.div
                className="kliqt-card"
                variants={fadeInUp}
                initial="initial"
                whileInView="animate"
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.1 }}
              >
                <div className="flex items-center mb-4">
                  <FileText className="h-6 w-6 text-kliqt-secondary mr-3" />
                  <h3 className="text-xl font-bold">Modifications</h3>
                </div>
                <p className="text-gray-300 mb-4">
                  We may modify these terms at any time. We'll notify you of significant changes 
                  via email or through our services.
                </p>
                <div className="text-sm text-gray-400">
                  <p>• 30-day notice for major changes</p>
                  <p>• Continued use implies acceptance</p>
                  <p>• Right to terminate if you disagree</p>
                </div>
              </motion.div>
            </div>
          </div>
        </section>

        {/* Termination */}
        <section className="py-20 bg-gray-900/50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              className="kliqt-card"
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div className="flex items-center mb-6">
                <div className="p-3 bg-orange-500/10 rounded-xl mr-4">
                  <AlertTriangle className="h-8 w-8 text-orange-400" />
                </div>
                <h2 className="text-3xl font-bold">Termination</h2>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-xl font-semibold mb-3 text-kliqt-secondary">
                    Your Right to Terminate
                  </h3>
                  <p className="text-gray-300 mb-4">
                    You may terminate your account at any time by contacting us or using the 
                    account settings in your portal.
                  </p>
                  <ul className="text-sm text-gray-400 space-y-1">
                    <li>• Immediate termination available</li>
                    <li>• Data export options provided</li>
                    <li>• No penalties for termination</li>
                  </ul>
                </div>
                
                <div>
                  <h3 className="text-xl font-semibold mb-3 text-kliqt-secondary">
                    Our Right to Terminate
                  </h3>
                  <p className="text-gray-300 mb-4">
                    We may terminate or suspend your account for violations of these terms, 
                    non-payment, or other legitimate reasons.
                  </p>
                  <ul className="text-sm text-gray-400 space-y-1">
                    <li>• Notice provided when possible</li>
                    <li>• Opportunity to cure violations</li>
                    <li>• Data retention for reasonable period</li>
                  </ul>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Contact Information */}
        <section className="py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              className="kliqt-card text-center"
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <h2 className="text-3xl font-bold mb-6">Questions About These Terms?</h2>
              <p className="text-gray-300 mb-8">
                If you have any questions about these Terms of Service or need clarification 
                on any provisions, please contact us.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/contact" className="kliqt-btn-primary">
                  Contact Us
                </Link>
                <a 
                  href="mailto:legal@kliqtmedia.co.uk" 
                  className="kliqt-btn-secondary"
                >
                  Email Legal Team
                </a>
              </div>
              
              <div className="mt-8 pt-8 border-t border-gray-800">
                <div className="text-sm text-gray-400 space-y-2">
                  <p><strong>Legal Department:</strong> legal@kliqtmedia.co.uk</p>
                  <p><strong>Address:</strong> 123 Tech Hub Lane, London, EC2A 4DP, United Kingdom</p>
                  <p><strong>Phone:</strong> +44 20 7946 0958</p>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Related Links */}
        <section className="py-20 kliqt-gradient-bg">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <motion.div
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <Scale className="h-16 w-16 text-kliqt-secondary mx-auto mb-6" />
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Related Legal Documents
              </h2>
              <p className="text-xl text-gray-300 mb-8">
                Review our complete legal framework to understand your rights and our commitments.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/privacy" className="kliqt-btn-secondary">
                  Privacy Policy
                </Link>
                <Link href="/" className="kliqt-btn-primary">
                  Back to Home
                </Link>
              </div>
            </motion.div>
          </div>
        </section>
      </div>
    </main>
  )
}